branch-defaults:
  mongo:
    environment: mindlogger-app-backend
    group_suffix: null
global:
  application_name: mindlogger-app-backend
  branch: mongo
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
