name: Deploy to dev on AWS EB
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r deploy.zip *.js *.json *.html *.css

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v3
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: mindlogger_mongo_atlas
        environment_name: mindlogger-atlas-dev
        version_label: $GITHUB_SHA
        region: us-east-1
        deployment_package: deploy.zip
